spring:
  # 配置数据源信息
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis_plus?serviceTimeZone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 1234
        datasource_2:
          url: jdbc:mysql://localhost:3306/mybatis_plus_1?serviceTimeZone=GMT%2B8&characterEncoding=utf-8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 1234


#spring:
#  #配置数据源
#  datasource:
#    #配置数据源类型
#    type: com.zaxxer.hikari.HikariDataSource
#    #配置连接数据库的信息
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybatis_plus?serviceTimeZone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 1234
#

#MyBatis-Plus相关配置
mybatis-plus:
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: t_
  #扫描通用枚举的包
  type-enums-package: com.qimu.mybatisplus.emums
